# End to End model draft 1

## Todo:
- Show visuaization on the difference of using transform and normalization

## Imports

In [1]:
import torch
import torch.nn as nn
import pandas as pd 
from torch.utils.data import DataLoader
import nibabel as nib
from project.preprocessing import z_score_normalization, NiftiToTensorTransform, get_transform
from project.training import split_train_val_datasets
from project.dataset import Dataset, VALDODataset

c:\Users\nigel\AppData\Local\Programs\Python\Python312\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.19 (you have 1.4.18). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()

ModuleNotFoundError: No module named 'project.training'

# =================================

## Import dataset and select target slices

**Gets the whole dataset from a specific location**

In [2]:
ds = Dataset()

### Generate targets

In [3]:
# Lood the raw rmi and maks of the data based on the number of cohors in the dataset
## Data  ds.load_raw_mri() can also be changed to ds.load_skullstripped_mri() for the preprocessed data
mri = ds.load_raw_mri()
masks = ds.load_cmb_masks()
# Get the slices of the MRIs 
slices = [nib.load(x).get_fdata().shape[2] for x in mri]

## Create a standard dataframe of the unprocessed data 
standard_df = pd.DataFrame({
    'mri': mri,
    'masks': masks,
    'slices': slices
})

In [4]:
standard_df.head(3)

,mri,masks,slices
0,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,35
1,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,35
2,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,35

**Function to generate all the target slices for each case**

In [5]:
def generate_target_slice(mri, masks, slices):
    if len(mri) != len(masks):
        print(f'Unequal amount of mri cases to cmb masks\t{len(mri)} to {len(masks)}')
    if len(mri) != len(slices):
        print(f'Unequal amount of mri cases to case slice counts\t{len(mri)} to {len(slices)}')

    ls = [(mri[i], masks[i], target) for i in range(len(mri)) for target in range(slices[i])]
    df = pd.DataFrame(ls, columns=['mri', 'masks', 'target'])
    # ls = [(case, target) for case, slices in zip(case, slices) for target in range(slices)]
    return df


df = generate_target_slice(mri, masks, slices)

In [6]:
df.head(3)

,mri,masks,target
0,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,0
1,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,1
2,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,2

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7986 entries, 0 to 7985
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   mri     7986 non-null   object
 1   masks   7986 non-null   object
 2   target  7986 non-null   int64
dtypes: int64(1), object(2)
memory usage: 187.3+ KB

**Double check if all the slices matches with the raw dataframe count**

In [8]:
ar_targets = df.groupby('mri').target.max()
ar_slices = standard_df.groupby('mri').slices.max()
(ar_targets == (ar_slices - 1)).all()

np.True_

#### Expport as metadata(CSV file)

In [9]:
# df.to_csv('targets.csv', index=False)

# ===============================================

In [10]:
data = pd.read_csv('targets.csv')

In [11]:
data.head(5)

,mri,masks,target
0,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,0
1,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,1
2,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,2
3,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,3
4,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,c:\Users\nigel\Documents\Thesis\Dataset\VALDO_...,4

In [12]:
data.shape

(7986, 3)

**7987 cases with 3 columns**
- Columns
    - mri
    - masks
    - target slice

## Transform the data

In [13]:
transform = NiftiToTensorTransform(target_shape = (512, 512), rpn_mode=True)
normalization = z_score_normalization

cases = data.mri
masks = data.masks
target = data.target

In [14]:
# dataset_raw = VALDODataset(
#     cases=cases,
#     masks=masks,
#     target=target
# )

TypeError: VALDODataset.__init__() missing 1 required positional argument: 'transform'

In [17]:
dataset_raw

Error loading image: 'NoneType' object is not callable

(None, None, None, None)

In [15]:
dataset_raw

In [16]:
dataset = VALDODataset(
    cases=cases,
    masks=masks,
    target=target,
    transform=transform,
    normalization=normalization,
)

In [21]:
dataset.__getitem__(5)

(tensor([[[[[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]]]],



         [[[[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]]]],



         [[[[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]]]],



         ...,



         [[[[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]]]],



         [[[[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]]]],



         [[[[0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            ...,
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.],
            [0., 0., 0.,  ..., 0., 0., 0.]]]]], dtype=torch.float64),
 tensor([[[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[154., 289., 194., 346.]]],


         [[[247., 310., 270., 334.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[268., 335., 291., 358.]]],


         [[[223., 303., 273., 334.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[145., 178., 170., 202.]]],


         [[[249., 206., 286., 316.]]],


         [[[258., 216., 289., 309.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[244., 293., 268., 318.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]],


         [[[  0.,   0.,   0.,   0.]]]]),
 np.int64(5),
 'c:\\Users\\nigel\\Documents\\Thesis\\Dataset\\VALDO_dataset\\mri_t2s_dir\\sub-101_space-T2S_desc-masked_T2S.nii.gz')

In [ ]:
print(type(dataset))
print(len(dataset))

In [ ]:
has_cmb = [1 if count > 0 else 0 for count in dataset.cmb_counts]

df_dataset = pd.DataFrame({
    'MRI Scans': dataset.cases,
    'Segmented Masks': dataset.masks,
    'CMB Count': dataset.cmb_counts,
    'Has CMB': has_cmb
})

In [ ]:
df_dataset.head(5)

### Stratified splitting

In [ ]:
train_dataset, val_dataset = split_train_val_datasets(
    df=df_dataset, 
    transform=transform
)

train_loader = DataLoader(
    train_dataset, 
    shuffle=True, 
    batch_size=batch_size,
    collate_fn=collate_fn
)

val_loader = DataLoader(
    val_dataset, 
    shuffle=True, 
    batch_size=batch_size,
    collate_fn=collate_fn
)